name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache Hugging Face models
      uses: actions/cache@v3
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-hf-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-hf-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Milvus services
      run: |
        docker compose -f docker-compose.yml up -d etcd minio milvus-standalone
        # Wait for etcd
        timeout 300 bash -c 'until curl -f http://localhost:2379/health; do sleep 5; done' || true
        # Wait for minio
        timeout 300 bash -c 'until curl -f http://localhost:9000/minio/health/live; do sleep 5; done' || true
        # Wait for milvus
        timeout 300 bash -c 'until curl -f http://localhost:9091/healthz; do sleep 5; done' || true
        
    - name: Run tests with pytest
      run: |
        pytest tests/ -v --cov=. --cov-report=xml --cov-report=html
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: evaluation-reports
        path: |
          reports/
          htmlcov/
