name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      milvus:
        image: milvusdb/milvus:latest
        ports:
          - 19530:19530
          - 9091:9091
        options: >-
          --health-cmd "curl -f http://localhost:9091/healthz || exit 1"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache Hugging Face models
      uses: actions/cache@v3
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-hf-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-hf-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with pytest
      run: |
        pytest tests/ -v --cov=. --cov-report=xml --cov-report=html
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: evaluation-reports
        path: |
          reports/
          htmlcov/
